export const GAME_ACTION_TYPES = {
  SET_QUOTE: 'game/SET_QUOTE',
  CLEAR_QUOTE: 'game/CLEAR_QUOTE',
  SET_ERRORS_COUNT: 'game/SET_ERRORS_COUNT',
  INCREMENT_ERRORS_COUNT: 'game/INCREMENT_ERRORS_COUNT',
  ADD_CHOSEN_LETTER: 'game/ADD_CHOSEN_LETTER',
  CLERAR_CHOSEN_LETTERS: 'game/CLERAR_CHOSEN_LETTERS',
  SET_GAME_STATUS: 'game/SET_GAME_STATUS',
  SET_GAME_START_TIME: 'game/SET_GAME_START_TIME',
}